[build]
  command = "yarn build"
  publish = "build"

[context.production.environment]
  REACT_APP_API_BASE_URL = "https://example.com"
  REACT_APP_API_STAGING_URL = "https://secondhand-be1-staging.herokuapp.com"
  REACT_APP_TOKEN_KEY = "SECONDHAND_BINAR_TOKEN"
